### ISSUE TITLE
Back button transitions in the wrong direction

### ISSUE THREAD

**Issue by petebacondarwin** [ajoslin/angular-mobile-nav#1]
Let me clarify that.  The "back" button on the demo page works as expected but if you use your browsers back function (i.e. button or Alt-Left, etc) then the transition looks like a forward transition.

**Comment by petebacondarwin** [comment]
Also the navigate services ought to track browser forward events.  At the moment if you browse forwards then the demo "back" button fails to do anything.

**Comment by ajoslin** [comment]
Hi Pete, thanks for poppin in with an issue. 

I made this not with browser apps in mind, but hybrid apps (eg phonegap or trigger.io), where there is no back for the browser. 

But I will look into getting the browser back button working anyway with window.onpopstate, definitely would be good to have for webapps.

**Comment by petebacondarwin** [comment]
Android devices do have a back button.  I don't know how PhoneGap deals
with that.

**Comment by ajoslin** [comment]
You can add an event listener for it which disables the default. Search for "backbutton" in navigate.js

**Comment by ajoslin** [comment]
Moved to #4
