### ISSUE TITLE
iPad (iOS 6.01) and Chrome issue

### ISSUE THREAD

**Issue by whitneyland** [ajoslin/angular-mobile-nav#12]
After the transition completes the page flashes.  See live example here:
    http://amnav.kissr.com

Not sure if this is related to #10.  Posted new since the other issue seems to not be reproducible on modern devices/browsers.

Any ideas?

**Comment by jrowny** [comment]
Try the pull request I made, just adding -webkit-backface-visibility. That seems to fix things for me.

**Comment by whitneyland** [comment]
really appreciate the help - but it's still there on chrome and iOS 6.

to duplicate, just switch back and forth a few times between page 1 and page 2.  I've added your pull request to the live code:  http://amnav.kissr.com

it seems like sometimes it works perfectly the first or second time but not after that.  weird.

**Comment by ajoslin** [comment]
Ok, so I think the problem was that every css page needs to keep its ending CSS after the animation ends.  I manually made every CSS class have that in the latest commit e01293e2d63259a2ef9592a8abf15688f2867fc1.

I tried it on your example @WhitneyLand and it seems better now.

**Comment by whitneyland** [comment]
Lets kick the tires and light the fires.  That last fix is testing out great on iOS 6 and Chrome desktop.

Woot.  thanks.

**Comment by revolunet** [comment]
@ajoslin : could be very nice to upgrade the official demo page with these fixes as it still flickers on Android :)

**Comment by ajoslin** [comment]
Yay, finally fixed! 

I updated the demo page now.  Thanks everyone for all the help and research, y'all are awesome :+1:

**Comment by revolunet** [comment]
thanks. unfortunately, still flickering on Android when clicking Back button.  (chrome stable on android 4.2)
- The first transition is OK
- Then when hitting back, we see immediatly the first screen and the transition starts.

Note it works perfectly on Chrome _beta_ for android.

Any idea how we should resolve this ?

**Comment by ajoslin** [comment]
Hmm.. You are correct.  It seems on android that the translate3d properties on the css classes apply themselves and override the webkit keyframe somehow. 
I need to be sure to test and android _and_ iOS.  I wish there was an automated way to do this...

**Comment by revolunet** [comment]
Do you think you can resolve this ? i can help you testing if you need

**Comment by ajoslin** [comment]
I probably won't have time to get to this until the weekend, so if you want to have a shot please go for it :-)

Try adding `-webkit-animation-fill-mode: forwards;` on all `.mb-page` and remove the custom `translate3d` that I put on each class.  I did this before and it worked, but it lagged. 

`-webkit-animation-fill-mode: forwards` ([documentation](https://developer.mozilla.org/en-US/docs/CSS/animation-fill-mode)) will do the same thing as the custom transforms I did on each class.  It just seems to lag a lot on mobile.  But if that fixes it on android, we have a (laggy) step forward!

If you make it there, try to tweak some more.

I also have an idea for a css hack if this doesn't work.

**Comment by ajoslin** [comment]
I am working on this today.  I have an idea.

**Comment by ajoslin** [comment]
Would someone be able to test with the latest commit on Android 4.1?  I was able to test on iOS and Android 2.2 browser and it works there.

**Comment by revolunet** [comment]
:+1:  OMG you did it, it works perfectly on Android 4.2.1 with chrome 18, congratz !

**Comment by revolunet** [comment]
works also nicely on android 4.0.3 with stock browser (not even chrome)

**Comment by ajoslin** [comment]
Awesome!  Does anyone have an older iOS device to test on for completeness?

**Comment by revolunet** [comment]
works correcly on iPhone 1 iOS3. the only problem is the 'Back' button not well positionned; its not on toolbar top left but top center... who cares about IOS3 anyway :)

**Comment by ajoslin** [comment]
Yeah, that happened on Android 2.2 too.  More of an iUI's CSS problem than framework problem.. but I should fix that anyway... thanks!!
