### ISSUE TITLE
Preload all templates defined in $routeProvider

### ISSUE THREAD

**Issue by ajoslin** [ajoslin/angular-mobile-nav#14]
We don't want to lazy load page templates in a mobile app.  Having a delay while a page is XHR loaded just looks bad on mobile.

Just need to add this code somewhere (probably a `.run` function on our module):

``` js
angular.forEach($route.routes, function(r) {
  if (!$templateCache.get(r.templateUrl)) {       
    $http.get(r.templateUrl).then(function(response) {
      $templateCache.put(r.templateUrl, response.data);                                                                                                                   
    });                              
  }
});
```

**Comment by whitneyland** [comment]
Are you talking about server based html or local html?  In other words is the delay still detectable using local html and local XHR in phonegap?

Not against new functionality, just talking it through...

**Comment by revolunet** [comment]
my 2cents: yes we dont want lazy loading in mobile :) but there are various server side tools or client side build tools (eg: grunt) that take care of placing the templates inside the main html to prevent lazy loading. Not sure that the mobile nav module should decide of that in any way.

**Comment by ajoslin** [comment]
Fair enough. It's probably a bit too heavy handed to add to this.

**Comment by ajoslin** [comment]
@Whitney I meant client based.
