### ISSUE TITLE
$anchorScroll not working with <mobile-view>

### ISSUE THREAD

**Issue by tribeca** [ajoslin/angular-mobile-nav#16]
As $anchorScroll is working automatically with the default ng-view it would be nice if it would work with mobile-view too. As I'm pretty new to angularjs I'm not sure if I could get it somehow to work.

**Comment by ajoslin** [comment]
I don't think that just using anchorScroll will be enough to solve it. We will need to remember scrollHeight in history somehow.  See https://github.com/ajoslin/angular-mobile-nav/issues/8

**Comment by ajoslin** [comment]
Closed since 8 is the relevant version of this issue
