### ISSUE TITLE
Chrome console errors in latest source

### ISSUE THREAD

**Issue by whitneyland** [ajoslin/angular-mobile-nav#21]
Line 235 of mobile-nav.js seems to generate an error because the reverse property does not exist in the conditional below.

This is without using the new reverse option at all.

Is there a config change we need to avoid the error?

 if (dest.reverse() || ($route.current && $route.current.$route.reverse)) {

**Comment by whitneyland** [comment]
Making this change seems to work and makes the error go away:

if (dest.reverse() || ($route.current && $route.current.$route && $route.current.$route.reverse)) {

Not sure if that's the proper solution though...

**Comment by ajoslin** [comment]
I fixed it in 255a97f23b2bbd30592d693252c7fbd08cff7a76

I really need to add tests when I have time.  That's next up :-)
