### ISSUE TITLE
click delay

### ISSUE THREAD

**Issue by gflarity** [ajoslin/angular-mobile-nav#27]
Hi,

This looks very useful. It seems a like there's a delay when you click something though. For a work around check out:
http://cubiq.org/remove-onclick-delay-on-webkit-for-iphone

**Comment by ajoslin** [comment]
Hi @gflarity, 

You're right, there is sometimes a noticeable page load delay on mobile, but it's not from clicking.  It's from compiling and inserting the next page into the DOM.  This delay is only noticeable when the next page has a lot of content to insert, though. There are several methods I am thinking of to fix this.

The code is pending a refactor at the moment.  Or I may just make a fork of [angular-ui/ui-router](https://github.com/angular-ui/ui-router).
