### ISSUE TITLE
carouFredSel and .mb-page { -webkit-backface-visibility: hidden; }

### ISSUE THREAD

**Issue by bennlich** [ajoslin/angular-mobile-nav#28]
I'm trying to stick a [carouFredSel](http://caroufredsel.dev7studios.com/) on one of my angular-mobile-nav pages. For some reason, the `-webkit-backface-visibility: hidden;` style of `.mb-page` makes the carouFredSel invisible. Is that style necessary for the angular-mobile-nav functionality?

**Comment by ajoslin** [comment]
This is unnecessary; it was an attempted fix for an earlier bug.  Fixed in 5ba5ec49447ee01228888f687557079846937b8a

**Comment by ajoslin** [comment]
I was wrong: Without -webkit-backface-visibility, android 2.x devices flicker on transition.  I put it back in @ 7dd291c064777448593a828acc90455ec88942b1
