### ISSUE TITLE
Broken history if redirection is active or route to navigate to is invalid

### ISSUE THREAD

**Issue by wzr1337** [ajoslin/angular-mobile-nav#29]
do not call  onRouteSuccess() if next is undefined or rediretTo is element of next.$route. The $routeChangeSuccess event is triggered twice if a redirection is active, like shown in this example: http://plnkr.co/edit/pZfw9tMhFqtaVPV9WJaz

```
/* 
 * Will listen for a route change success and call the selected callback
 * Only one listen is ever active, so if you press for example 
 * /link1 then press back before /link1 is done, it will go listen for the back
 */
self.onRouteSuccess = angular.noop; //default value
$rootScope.$on('$routeChangeSuccess', function($event, next, last) {
  if (next && next.$route && ! ('redirectTo' in next.$route)) {
    self.onRouteSuccess($event, next, last);
  }
});
```

**Comment by ajoslin** [comment]
Hey @wzr1337,

I fixed this a few weeks ago, are you using an old version? :-)

https://github.com/ajoslin/angular-mobile-nav/blob/master/src/navigate.js#L54

**Comment by wzr1337** [comment]
Tanks @ajoslin i was using an outdated version, sorry.
