### ISSUE TITLE
How to contribute?

### ISSUE THREAD

**Issue by bennlich** [ajoslin/angular-mobile-nav#30]
Hey. I'd like to send a pull request with a few changes, but I'm new to jshint and uglify-js. Can you explain the process? Also, does the last line of the readme mean you want pull requests for the gh-pages branch only?

Thanks for the lib!

**Comment by ajoslin** [comment]
Hi @bennlich.

Do you have nodejs installed?  We use node's package manager, called npm, to get jshint, which will check that the javascript is syntax-error-free.  Then uglifyjs minifies the code.

Here are more detailed steps.
1. Install nodejs from http://nodejs.org/
2. Once it's done, you can go to your command line and type `npm install -g jshint uglifyjs` to add `jshint` and `uglifyjs` commands globally
3. Do whatever changes you like, then in your command line cd to the `angular-mobile-nav` folder and run `make`.
4. If the js files pass jshint, you will now have a `dist` folder.  You can test out your code at `dist/index.html`.

**Comment by ajoslin** [comment]
Don't worry about the last line with the gh-pages thing.

**Comment by bennlich** [comment]
Thanks for the quick reply, @ajoslin!

Also, it looks like uglifyjs is now called uglify-js in npm.

**Comment by bennlich** [comment]
Hey, @ajoslin. When I run `make`, jshint finds a bunch of errors in transition.css:

```
src/transition.css: line 5, col 1, Expected an identifier and instead saw '.'.
src/transition.css: line 5, col 2, Missing semicolon.
src/transition.css: line 5, col 9, Missing semicolon.
src/transition.css: line 6, col 13, Label 'position' on absolute statement.
src/transition.css: line 7, col 10, Label 'width' on 100 statement.
src/transition.css: line 7, col 14, Expected an identifier and instead saw ';'.
src/transition.css: line 7, col 15, Missing semicolon.
src/transition.css: line 8, col 11, Label 'height' on 100 statement.
src/transition.css: line 8, col 15, Expected an identifier and instead saw ';'.
src/transition.css: line 8, col 16, Missing semicolon.
src/transition.css: line 15, col 1, Unexpected '@'.
src/transition.css: line 16, col 8, Expected '}' to match '{' from line 16 and instead saw '-'.
src/transition.css: line 16, col 9, Missing semicolon.
src/transition.css: line 16, col 25, Missing semicolon.
src/transition.css: line 16, col 25, Expected '(end)' and instead saw ':'.
```

Does jshint think it's looking at javascript?

**Comment by ajoslin** [comment]
yeah..  I'll push a fix to make sure it only read JS files.  It doesn't do that on my computer for some reason.

**Comment by ajoslin** [comment]
Fixed in 7dd291c064777448593a828acc90455ec88942b1

**Comment by bennlich** [comment]
Awesome, thanks. And when you test the files in dist/, do you move dist/ to your ~/Sites/ directory?

**Comment by ajoslin** [comment]
You need to host the files somehow, because angularjs is trying to GET templates and the browser won't let you do that on local file server.

If you have python installed, the easiest way is to cd to the dist directory and type `python -m SimpleHTTPServer`, then navigate to `http://localhost:8000` in the browser.  `python -m SimpleHTTPServer` will just host a simple static file serving server at the current directory.
