### ISSUE TITLE
Not working with AngularJS 1.0.6

### ISSUE THREAD

**Issue by wzr1337** [ajoslin/angular-mobile-nav#34]
Since AngularJS 1.0.6 the $route property on the route object is deprecated.

https://github.com/angular/angular.js/commit/6f71e809141bf89501e55c378921d6e7ec9512bc

I got it working by replacing next.$route with $route. It works with AngularJS 1.0.4 and 1.0.6. I am not sure how to fix the transistion reversing.

**Comment by ajoslin** [comment]
I noticed this too; I will work on this on tomorrow! Thanks.

**Comment by ajoslin** [comment]
Fixed in 238c3abd557630032e496595c53417dfab3cf45c
