### ISSUE TITLE
.mb-page flashes in reverse transition

### ISSUE THREAD

**Issue by fanals** [ajoslin/angular-mobile-nav#35]
At the end of a reverse transition .mb-page is disappearing and reappearing in less than a second which causes a inelegant "flash". It happens randomly which was difficult for me to debug but I finally found that **-webkit-transform: translate3d(-100%, 0, 0);** in **mb-slide.mb-out** was causing it. Commenting the line fixes the issue.

**Comment by ajoslin** [comment]
Hi @fanals! Thanks for looking into this.

What device does it flash on?  That line was actually preventing a flash on Android 2.x, I think. :eyes:

**Comment by fanals** [comment]
Hi @ajoslin :) It's on iOS 6

**Comment by ajoslin** [comment]
I'm not able to reproduce the flash.  Could you create a jsfiddle or plunker?

**Comment by fanals** [comment]
In fact when I run my app in chrome it also flashes at random. I'll try to reproduce it in a jsfiddle as soon as possible.

**Comment by ajoslin** [comment]
@fanals any progress?

**Comment by fanals** [comment]
I still cannot reproduce it outside of my app. As I'm not allowed to publish the code I guess you can close the issue. I tried to debug the past hour and I couldn't isolate the bug, sorry I give up.

**Comment by ajoslin** [comment]
Ok, thanks for trying.

**Comment by ajoslin** [comment]
Do you have the latest version of the css in your app, with the -webkit-backface-visibility fix?

**Comment by fanals** [comment]
yes
