### ISSUE TITLE
make it availble through bower

### ISSUE THREAD

**Issue by wzr1337** [ajoslin/angular-mobile-nav#36]
Please be so kind and register mobile nav on bower.

Thanks

**Comment by ajoslin** [comment]
Added the wrong package - a different repo of mine.  I'll add this one later.

**Comment by galetahub** [comment]
There is no tags in the repository and bower can't install it:
https://www.evernote.com/shard/s278/sh/6ccd248c-1209-4616-8696-3c6811edc38a/201bc63acb4382f58445ce5683e41e77

Please, create tag v1.0.0

**Comment by AlmogBaku** [comment]
Hey @ajoslin !,
Can you please create tag named `1.0.0` so we can import it via bower?...

**Comment by wzr1337** [comment]
Even with no tags you can install it by

```
    $ bower install angular-mobile-nav#* --save
```

This will persist the dependency in your bower.json aswell

**Comment by AlmogBaku** [comment]
I used "master" for now, and it seems work.
But anyway adding tag is required
