### ISSUE TITLE
I can't make the demo show anything

### ISSUE THREAD

**Issue by FdezRomero** [ajoslin/angular-mobile-nav#38]
Hi guys!

I cloned the repo on my local OS X web server and I can't make the demo show anything when I access the url on localhost, is like it's not loading the `content/home.html`template on the default path (`/`). I'm using the `mobile-nav.js` and `mobile-nav.css` from the demo website (at the `gh-pages` branch) and haven't been able to make it work.

Am I missing something? I left the demo as-is, just adding these 2 files. Any help would be appreciated.

Thanks!

**Comment by ajoslin** [comment]
Hi Fdez,

Try running `make` and then run `dist/index.html`.

**Comment by FdezRomero** [comment]
Thanks @ajoslin, working perfectly now.

Please note that the install command on the README.md has a typo, it should be `npm install -g jshint uglify-js` (note the dash in `uglify-js`).
