### ISSUE TITLE
doesn't work on angular 1.1.4

### ISSUE THREAD

**Issue by lancevo** [ajoslin/angular-mobile-nav#40]
if you swap out the angular in your demo with 1.1.4, it doesn't work. I took me a while to confirm it.

**Comment by ajoslin** [comment]
Thanks Lance! I will try to resolve this today or tomorrow.

**Comment by ajoslin** [comment]
It works now - the demo is even in 1.1.4.

**Comment by lancevo** [comment]
Awesome. I can't wait to give it a try. Thanks
