### ISSUE TITLE
Memory leak after refresh of page

### ISSUE THREAD

**Issue by clark-pan** [ajoslin/angular-mobile-nav#42]
I think i may have found some buggy behaviour is a user refreshes on a page and presses the browser's back button.

steps to reproduce:
1) go to http://ajoslin.github.io/angular-mobile-nav/
2) navigate a few pages
3) refresh the browser
4) press the back button on the browser

Now if you inspect the dom, there will be multiple 'mp-page' elements that will never be removed.

Tested in 27.0.1453.56 beta

**Comment by ajoslin** [comment]
Hmm, this isn't really made to be used with the browser - more with something like phonegap and hybrid apps.  The browser back button isn't handled well right now.

I'm not sure why this messes up, though...

**Comment by clark-pan** [comment]
I've had a look at this issue and its related to the defaultRouteSuccess method. In the defaultRouteSuccess, the current page is not passed forward, which causes the current page not to be removed from the DOM.
