### ISSUE TITLE
TabGroup Example?

### ISSUE THREAD

**Issue by aaronksaunders** [ajoslin/angular-mobile-nav#43]
I have been searching for a nice integration with angularjs that will support mobile tabgroup UI, can that be done with this framework? Is there an example somewhere?

thanks

**Comment by ajoslin** [comment]
It could be done with this, but it would require some work.

I would recommend [angular-ui/ui-router](http://github.com/angular-ui/ui-router) for this -- ui-router has nested views, which are perfect for tab groups. Each tab would have its own view state, with its own history.

Unfortunately, using ui-router with ng-animate to make nice mobile transitions currently doesn't work too well.  Until they resolve angular-ui/ui-router#96, angular-mobile-nav will still be useful for animation purposes.  Once they resolve that issue, someone (maybe me) can write nice easy mobiley animation javascript/css for ui-router and the world will be happy again.

So short answer: Use ui-router nested views for tab groups, use angular-mobile-nav for animations.  you can't win atm :crying_cat_face:
