### ISSUE TITLE
Demo page not working

### ISSUE THREAD

**Issue by Jehu** [ajoslin/angular-mobile-nav#44]
i get an empty page in chrome.

**Comment by ajoslin** [comment]
It works for me - are you talking about http://ajoslin.github.io/angular-mobile-nav, or locally? 

If you're doing it locally.. I added another note to the readme:
- To get the demo to work, you first have to run `make`, then open the demo at `dist/index.html`.

**Comment by Jehu** [comment]
i talked about http://ajoslin.github.io/angular-mobile-nav
Today it works again.
