### ISSUE TITLE
mobile-view stays empty

### ISSUE THREAD

**Issue by Jehu** [ajoslin/angular-mobile-nav#45]
No contents will be rendered inside the mobile-view directive.
I use Angular 1.0.6 and the current angular-mobile-nav from github.
Tested on Android default browser, Android Chrome and Desktop Chrome.

**Comment by ajoslin** [comment]
This only works on angular 1.1.4+ at the moment.  I will add that to the README, thanks:)

**Comment by Jehu** [comment]
good to know...
thanks.
