### ISSUE TITLE
mobile-view is empty if you use a controller specified in routeprovider

### ISSUE THREAD

**Issue by utunga** [ajoslin/angular-mobile-nav#46]
when i set up the ng-controller via the routeProvider config (in app.js for example) like this:

```
.config(function ($routeProvider) {
  $routeProvider
    .when('/', {
      templateUrl: 'views/main.html',
      controller: 'AccountCtrl'
    })
})
```

the mobile-view element is empty and we get no errors to indicate what went wrong.

When, on the other hand, I set up the controller via directive directly in the html (in index.html for example) like this:

```
<body ng-controller="MainCtrl">
```

All the content comes back.

This is with angularjs 1.1.4x and very few other dependencies.

(I went to some trouble to upgrade a fairly vanilla bower/yeoman install of angular to angular.1.1.4 so I could resolve this but turns out, in this case, the invisibility problem is the same in either version).

**Comment by utunga** [comment]
I don't especially mind specifying the controller in html but want to be able to vary the controller depending on context.

**Comment by ajoslin** [comment]
Weird problem. So it does work when you have some sort of ctrl on the body?

## I will be able to look at this later today, but have you tried just puttin a wrapper controller called AppCtrl or something on body?

Andy Joslin
919-723-8919

**Comment by utunga** [comment]
hi Andy thanks for getting back to me

I've discovered that if I do this in the html..

```
<html ng-app="pocketMoneyApp">
...  
 <body ng-controller="MainCtrl">
    <mobile-view></mobile-view>
  </body>
```

and this in the app.js

```
angular.module('pocketMoneyApp', ['ajoslin.mobile-navigate'])
.config(function ($routeProvider) {
  $routeProvider
    .when('/', {
      templateUrl: 'views/main.html',
      controller: 'AccountCtrl'
    });
})
.controller('MainCtrl', function($scope, $navigate) {
  $scope.$navigate = $navigate;
})
.controller('AccountCtrl', function ($scope, $navigate) {
    $scope.$naviage = $navigate;
    $scope.awesomeThings = [
      'hello from account controller'
    ];
});
```

Then I can see 'hello from account controller' in the browser (so I guess  the AccountrController is being correctly injected into mobile-view by the $routeProvider stuff).

When I remove the ng-controller directive in the html again by doing this.. 

```
 <body>
    <mobile-view></mobile-view>
  </body>
```

.. then I'm back to the white screen of death ;-)

So yeah I guess having 'some sort of ctrl on the body' solves the problem but lets you dynamically configure the controller in the route provider.. which is a workaround.

**Comment by ajoslin** [comment]
Aha, I understand now!  $navigate is never instantiated unless you inject it somewhere. You could try a 'run' function that injects $navigate. 

I will probably add a run function to the mobile-nav core, or perhaps just make the help let you know about this.

**Comment by doroncy** [comment]
i can not get it to work... the mobile-view directive is empty.
i tried to remove the controller from the routes and

**Comment by ajoslin** [comment]
Hi @doroncy , are you injecting $navigate anywhere?

**Comment by doroncy** [comment]
thanks.. working now.
by the way, i think the animations doesn't use the GPU, is there any plans
to update the animations to use css translate instead of transitions?

**Comment by ajoslin** [comment]
Glad you got it working :-)
.. and it uses GPU: https://github.com/ajoslin/angular-mobile-nav/blob/master/mobile-nav.css#L17

**Comment by kashiru** [comment]
@doroncy can you share how you got it working? I am facing the same issue

**Comment by utunga** [comment]
@kashiru is your problem that the mobile-view is empty, in general, or that its empty only when you don't specify a controller in the HTML (ie you specify the controller in the module config/ route provider). Because if its the latter the workaround (for now) is just to specify controller in the html. I have a controller specified in the html called 'WorkAroundController' 

```
 <body ng-controller="WorkAroundController">
```

.. that does nothing except this

```
.controller('WorkAroundController', function($scope, $navigate) {
  $scope.$navigate = $navigate;
})
```

This leaves me free to configure my routes with different controllers for each in the usual way *(see above for eg).

**Comment by kashiru** [comment]
@utunga Thanks, that approach worked, i was delayed in figuring it out due to another unrelated issue with the framework where it does not seem to route properly if there is a query string in the path.

**Comment by ajoslin** [comment]
That issue will be fixed when it uses ui-router.

**Comment by kashiru** [comment]
What do you mean ui-router? is this available to use now, or something that will be released in future? 

thanks, this tool is awesome.
