### ISSUE TITLE
Force creation of a navHistory entry before redirecting

### ISSUE THREAD

**Issue by fanals** [ajoslin/angular-mobile-nav#49]
Hi, I'm trying to handle a logged in redirection and still be able to call `$navigate.back()` to log out.

For example: The user goes to / and if he is logged in it redirects to /home. Then if he wants to log out I call `$navigate.back()` but here nothing happens as the navHistory is empty.

`$rootScope.$on("$routeChangeStart", function(event, next, current) {
     if (user_logged_in)
          $navigate.go('/home');     
});`

For the moment I added those two lines in the `go` function.

`if (!navHistory.length)
   navHistory.push(new Page($location.path()));`

Is there a better way to do it ? Thanks

**Comment by ajoslin** [comment]
The way I would do it in this case is not with a back.  I would just do a `go` to the logout page with a reverse transition.

`$navigate.go('/login', true);`

**Comment by fanals** [comment]
Oh well that was easy, never used the reverse transition before and didn't think about it. Thanks
