### ISSUE TITLE
What is nodejs used for?

### ISSUE THREAD

**Issue by madzgo** [ajoslin/angular-mobile-nav#50]
I'm trying to figure out why does this module require nodejs?

Could it be done without it?

I was looking to make a demo in Phonegap and create an Android app, but Phonegap doesn't support node js.

**Comment by ajoslin** [comment]
Node.js is simply used to build it. Node.js has common JavaScript utilities like uglifyjs (minify code) and jshint (check if JavaScript is good). To use it, you need nothing but the build files. 

## 

Andy Joslin
from my mobile

**Comment by madzgo** [comment]
Can I somehow get the built files and use them instead?

I'm actually trying to make this app work without nodejs
https://github.com/comoyo/ffos-list-detail

**Comment by ajoslin** [comment]
Yes, the built files are in the project root
