### ISSUE TITLE
Trigger transition from route controller

### ISSUE THREAD

**Issue by fanals** [ajoslin/angular-mobile-nav#51]
Hi @ajoslin,
When I do a slide transition on a page containing a lot of pictures, the transition does not look good. I would like to trigger the transition only when all pictures have finished loading.
Is there a way of doing it ? If not can you guide me into solving this problem.
Thanks

**Comment by fanals** [comment]
For the moment I'm doing it like that:

``` javascript
insertPage(dest);
$rootScope.$on('$doTransition', function() {
  currentTrans = changePage(dest, source, reverse);
});
```

Inside insertPage I set the next element to `display: none;` and inside `changePage` I set it back to initial.

So now I just need a way of bypassing the `$rootScope.$on('$doTransition')` if not needed.

**Comment by fotomut** [comment]
Perhaps you can use promises to determine a certain level of page load that
is adequate for a transition.

**Comment by ajoslin** [comment]
How about something like this:

App code:

``` html
<body ng-controller="AppCtrl">
  <mobile-view defer-transition="transitionWait()">
  </mobile-view>
</body>
```

``` js
function AppCtrl($scope, $q) {
  $scope.transitionWait = function() {
    var deferred = $q.defer();
    images.onLoad(deferred.resolve);
    return deferred.promise;
  };
}
```

Library code:

``` js
var nextPage = insertPage();
var deferTransition = scope.$eval(attrs.deferTransition) || $q.when();

nextPage.element.css('display' ,'none');
deferTransition.then(function() {
  nextPage.element.css('display', '')
  doTransition();
});
```

I'll implement this and push it to a branch and you can try it out.

**Comment by ajoslin** [comment]
Actually, it should probably be defined in the $route, like resolve ...

But we'll use this for now.

This code needs refactoring haha :-)

**Comment by ajoslin** [comment]
Try out 00f02fc83326170521ae35f77443c55658966606 on the `defer-transition` branch.  I tested it a bit with the demo, lmk if it works for you.

In the next version, you'll be able to have resolves in $routeProvider which run before or after the page is inserted.  The normal kind will delay dom insertion, the other will delay transition.

**Comment by fanals** [comment]
Perfect, works like a charm :) . At first I lost 10 minutes wondering why it was not working. Forgot the $apply when resolving.

And I changed to `dest.scope` on this line:

`var deferTransitionPromise = dest.scope.$eval(attrs.deferTransition) || $q.when();`

**Comment by ajoslin** [comment]
Landed in master
