### ISSUE TITLE
nav is undefined - android back button

### ISSUE THREAD

**Issue by maxgalbu** [ajoslin/angular-mobile-nav#53]
using angular-mobile-nav under android, at the line https://github.com/ajoslin/angular-mobile-nav/blob/master/mobile-nav.js#L12 nav is not defined, so the backbutton does nothing.

I've tried to do:

``` javascript
angular.module('ajoslin.mobile-navigate')
.run(function($navigate) {
  //Android back button functionality for phonegap
  document.addEventListener("deviceready", function() {
    document.addEventListener("backbutton", function() {
      var backSuccess = $navigate.back();
      if (!backSuccess) {
        navigator.app.exitApp();
      }
    });
  });
});
```

but it does nothing.

**Comment by ajoslin** [comment]
Woops! Fixed in 5f5cd1212b8c738b55620a05a4b44fb056b69988

This is why I need tests .. next version will .. :-)

**Comment by maxgalbu** [comment]
Thanks!
Just a fix, the inject array at [#L231](https://github.com/ajoslin/angular-mobile-nav/blob/5f5cd1212b8c738b55620a05a4b44fb056b69988/mobile-nav.js#L231) is missing a '$q'

**Comment by ajoslin** [comment]
Thankya, pushed that.
