### ISSUE TITLE
Slide Out Navigation

### ISSUE THREAD

**Issue by whitneyland** [ajoslin/angular-mobile-nav#56]
Slide out navigation as used in the Path and Facebook apps is becoming a common pattern.

Wondering if you have thought of how this might work in Angular? 

Do you think it's a concept that fits easily within this project, or ui-router, or something that requires more fundamental changes?

I'm going to start experimenting so I'm hoping gather the thoughts of others as I go.

Thanks-

**Comment by ajoslin** [comment]
Snap.js is the best. and it's relatively easy to hook up with angular

https://github.com/jakiestfu/Snap.js/

**Comment by whitneyland** [comment]
Andy you may be the fastest person on GitHub :).  Snap.js does look pretty cool.

Did you create a new directive to use it, or just found a way to fit it in as is?

**Comment by whitneyland** [comment]
Btw, for anyone who hasn't seen this:
https://github.com/jtrussell/angular-snap.js-bower

**Comment by ajoslin** [comment]
nice! Good to know that someone made something already :-)
