### ISSUE TITLE
android bug orange outline highlight

### ISSUE THREAD

**Issue by dryaf** [ajoslin/angular-mobile-nav#57]
Disable orange outline highlight on focus
on a galaxy s 3 android 4.1 when i click on a link its highlighted orange
this fixes it

button, button:hover, li:hover, a:hover , li , a , *:hover, *
{
    -webkit-tap-highlight-color: rgba(0, 0, 0, 0) !important;
}

got it from here
http://stackoverflow.com/questions/5210481/disable-orange-outline-highlight-on-focus

**Comment by dryaf** [comment]
but adds flickering of the  page to android 2.3.6 :-/    galaxy s1
uuuh this phonegap stuff is tricky

**Comment by ajoslin** [comment]
Haha, anything to do with android 2.x is tricky :-)

**Comment by ajoslin** [comment]
Were you able to resolve this?  I never had this problem in my own css.
