### ISSUE TITLE
How to animate between ng-includes

### ISSUE THREAD

**Issue by pabloleone** [ajoslin/angular-mobile-nav#58]
Hi!,

I have a page with two tabs and another tabs in each tab.

Page
-- MainTab
---- tab
---- tab
-- MainTab
---- tab
---- tab
---- tab

I want to add transitions between each tab and MainTab too.

Is that possible with this module?

Thank you vert much.

**Comment by ajoslin** [comment]
It sort of is... you can use the $change service.  You would be better off using ng-animate though.  And this doesn't use that currently.
