### ISSUE TITLE
Make transition definable in $routeProvider.when()

### ISSUE THREAD

**Issue by ajoslin** [ajoslin/angular-mobile-nav#6]
Idea is straight from the newest version jquery mobile angular adapter by tigbro: https://github.com/tigbro/jquery-mobile-angular-adapter/blob/master/Changelog.md

Syntax would be:

``` js
$routeProvider.when("/page1", {
  controller: 'MyCtrl',
  transition: 'modal'
});
```

**Comment by jrowny** [comment]
It'd be nice if this was still overridable via navigate.go in case I don't always want to use the same transition.

**Comment by ajoslin** [comment]
Yeah, good idea.

**Comment by ajoslin** [comment]
Done in a9cdb8d1d1c7e2a2cb16d752c7dff07c1df1267c
