### ISSUE TITLE
Exception on initial page load

### ISSUE THREAD

**Issue by matthias-001** [ajoslin/angular-mobile-nav#62]
Seems to be a similar issue like issue:
Exception on $routePrivder.otherwise processing

On initial page load I get the following error:
TypeError: Cannot read property 'reverse' of undefined at changePage

angularjs routing:
...
.config(['$routeProvider', function($routeProvider) {
    ...
    $routeProvider.otherwise({redirectTo: '/'});
}]);

To resolve this issue I had to change the following line in the changePage function:
var current = $route.current ? $route.current.$$route : {};
to
var current = ($route.current && $route.current.$$route) ? $route.current.$$route : {};

(I am pretty sure the initial page load should not even trigger this function, so this actually just seems to be a fast workaround.

using:
AngularJS 1.1.5 (unstable) and Eclipse, Android 4.2.2

kind regards,
matthias

**Comment by ajoslin** [comment]
Thanks, fixed in https://github.com/ajoslin/angular-mobile-nav/commit/97afb4b66c14201a9b9a47a452c08d7cdb4bc00e
