### ISSUE TITLE
Using Grunt instead of Make

### ISSUE THREAD

**Issue by bugwelle** [ajoslin/angular-mobile-nav#64]
What about using `Grunt` (v0.4.x) instead of `Make`?
I prefer it since it's NodeJS based. 

What do you think? :)

Regards,
Andre

**Comment by ajoslin** [comment]
https://github.com/ajoslin/angular-mobile-nav/blob/master/README.md#state-of-this-project-as-of-july-2013

I'm not planning on putting much work into this project.

But if you want to open a PR with a working Gruntfile, I would accept it :-)

**Comment by bugwelle** [comment]
oh :/
I haven't read that... 
I don't like JQM. It uses too many elements and classes. Does angular-jqm so, too? (I haven't looked into the code of it)
@ajoslin : Is there any demo? And, how far is it? Can we use it already? :)

Thanks,
Andre :)

**Comment by ajoslin** [comment]
@archer96 you should check out the project itself :-) https://github.com/opitzconsulting/angular-jqm - it is ready to use for development but not releasing yet, still under rapid changing.
