### ISSUE TITLE
adding Changelog

### ISSUE THREAD

**Issue by bugwelle** [ajoslin/angular-mobile-nav#65]
What about adding a Changelog (to README) ? :)
For example: if the directory structur changes or the filename changes, ...?

Regards,
Andre

**Comment by ajoslin** [comment]
I added a state of this project section: https://github.com/ajoslin/angular-mobile-nav/blob/master/README.md#state-of-this-project-as-of-july-2013

So a changelog probably won't happen :smile:

If you would like to open a PR with a changelog I guess I might accept it :-)
