### ISSUE TITLE
about inline template by ng-template

### ISSUE THREAD

**Issue by rainoxu** [ajoslin/angular-mobile-nav#66]
Hey, I put my templates of each views in the same page wrapped by `<script type="text/ng-template"></script>` , I found it did not run correctly, I checked your demo and found that:

```
.run(function($route, $http, $templateCache) {
  angular.forEach($route.routes, function(r) {
    if (r.templateUrl) { 
      $http.get(r.templateUrl, {cache: $templateCache});
    }
  });
})
```

So, the template should be loaded by xhr each time?

**Comment by ajoslin** [comment]
Doing it with the script tags will work fine. I just did it that way in the
demo for laziness's sake :)

On Friday, July 12, 2013, RainoXu wrote:

> Hey, I put my templates of each views in the same page wrapped by <script
> type="text/ng-template"></script> , I found it did not run correctly, I
> checked your demo and found that:
> 
> .run(function($route, $http, $templateCache) {
>   angular.forEach($route.routes, function(r) {
>     if (r.templateUrl) {
>       $http.get(r.templateUrl, {cache: $templateCache});
>     }
>   });
> })
> 
> So, the template should be loaded by xhr each time?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/ajoslin/angular-mobile-nav/issues/66
> .

## 

...sent from my etch-a-sketch

**Comment by rainoxu** [comment]
thx, I made some mistakes... It now works well :)
