### ISSUE TITLE
Access $navigate from outside the html code

### ISSUE THREAD

**Issue by omri-shaiko** [ajoslin/angular-mobile-nav#70]
How can i access the $navigate from outside the html?

Thanks

**Comment by ajoslin** [comment]
It's just a service, so inject it :-)

function MyCtrl($scope, $navigate) {
}

**Comment by omri-shaiko** [comment]
Thanks, i didn't explain myself properly.
How can i use the $navigate from outside angular, for example from the console in chrome dev tools?

My problem is that i have a function inside a script which is not a angular script, and i want to use the $navigate from there..

Thanks again!

**Comment by ajoslin** [comment]
angular.injector.get('$navigate').go('/abc');
angular.element(document).scope().$apply();

**Comment by omri-shaiko** [comment]
Are you sure? i'm getting an error. (Tried also in the demo)

**Comment by omri-shaiko** [comment]
Working! thanks!
