### ISSUE TITLE
Blank page after slide & horizontal scrollbar

### ISSUE THREAD

**Issue by artworkad** [ajoslin/angular-mobile-nav#72]
I just tested the demo on two android devices

```
1. Samsung Galaxy S2,  Android 4.1.2 (Browser v4.1.2-I9100XWLSD)
2. LG Optimus HD 4X, Android 4.1.2 (Browser v4.1.2)
```

A: On device 2, the lg, the demo produced following issue: when you navigate after you loaded the demo first time, at the bottom of the page appears a horizontal scrollbar. It disappears as soon as the animation has finished. When you navigate back the scrollbar appears again. When you navigate again, the scroll wont appear. This is strange. After the 4th navigation the scrollbar is gone and does not appear anymore.

Maybe this is because of the lazy page rendering?

```
I tried to add overflow: hidden to mb-page and mb-slide I even did
* { overflow: hidden } with no difference.
```

---

B: On device 1 the demo is completely broken. On initial load the demo displays fine, it still displays fine when you navigate first time. However when you navigate back you get a blank white page.

---

When I wrap my app with phonegap and install it as native app on both devices the same issues above appear. 

![screenshot_2013-08-03-19-22-30](https://f.cloud.github.com/assets/524580/905962/d2c2affa-fc61-11e2-9870-4b923491df51.png)

How can samsung screw up the native android browser? :-1: 

---

Any chance to fix this?

**Comment by artworkad** [comment]
Found bad news

> Here’s the thing: CSS animations are supported by Android devices — but only if a single property is changed. As > soon as you try to animate more than one property at once, the entire element disappears. In non-native Android > browsers, the element will be visible for the duration of the animation, but will hide immediately after it’s finished. 

This is known issue for android > 4.0 and as I just tested also for android 4.0.3 and 4.1.2 (only on samsungs custom build). Read more on http://daneden.me/2011/12/putting-up-with-androids-bullshit/

**Comment by artworkad** [comment]
Another nice article addressing this problems : http://webdesign.tutsplus.com/tutorials/htmlcss-tutorials/css3-animations-the-hiccups-and-bugs-youll-want-to-avoid/

**Comment by artworkad** [comment]
## Disappearing views

On android we can animate only one property at a time, so we need to modify

```
.mb-slide.mb-in.mb-reverse {
  -webkit-animation-name: slideOutToRight;
  //-webkit-transform: translate3d(100%, 0, 0);
}

.mb-slide.mb-out {
   -webkit-animation-name: slideOutToLeft;
  // -webkit-transform: translate3d(-100%, 0, 0);
}
```

## Overlaying views

This produces a new problem, on android views are overlaying each other. After a whole day of debugging o.O I tracked the problem down to this:

```
var ANIMATION_END = "animationName" 
     in document.documentElement.style ? "animationend" :    "webkitAnimationEnd";
```

when I change it to this:

```
var ANIMATION_END = "webkitAnimationEnd";
```

it works for me on samsung too :+1: 

## Horizontal scrollbar

By using

```
var ANIMATION_END = "webkitAnimationEnd";
```

the scrollbar is gone too :tada: 

## Wrapped in PhoneGap

Combined with this https://github.com/ajoslin/angular-mobile-nav/pull/73 you can wrap your project with phonegap and use angular-mobile-nav without issues. Many thanks to ajoslin :yum:

**Comment by ajoslin** [comment]
Ah, our firefox support broke old android.  That sucks.  I wish I had tests, sorry :-)  I will commit fix soon.

**Comment by ajoslin** [comment]
We use $sniffer now - undocumented service that angular core uses - https://github.com/angular/angular.js/blob/master/src/ng/sniffer.js

**Comment by fabiotrech** [comment]
I had the same problem with the current version. I solved as follows.

``` js
var ANIMATION_END = function () {
        var events = {
            'animation': 'animationend',
            'webkitAnimation': 'webkitAnimationEnd'
        };

        for (var evt in events) {
            if (evt in document.documentElement.style) {
                return events[evt];
            }
        }

        return '';
    } ();
```

**Comment by cauboy** [comment]
@maztercom Thanks for your code-snippet. It seems to work fine now.

**Comment by bugwelle** [comment]
@ajoslin Could you update [`mobile-nav.js`](https://github.com/ajoslin/angular-mobile-nav/blob/master/mobile-nav.js) with this fix, please? :)
