### ISSUE TITLE
Usage is not Clear

### ISSUE THREAD

**Issue by sonoman** [ajoslin/angular-mobile-nav#79]
Could you help in in implementing this in my current Angular Project ? I read your instructions, but when I go to the demo, I see several other modifications (like ng-init, and the ngTap directive)
What would be the minimal way of using it ? Do you need the initialization directive ( ng-init="angular='angular-mobile-nav'")

**Comment by ajoslin** [comment]
Hi sonoman,
did you figure this out?

**Comment by sonoman** [comment]
Hey ! Most of it....i implemented the directive ng-tap as you demoed, and it's triggering....although i cannot make it render inside <webview> tag....trying to do some tests because i have a mix of controllers that is probably causing the problem
One question...is there a way to use $navigate without implementing this new ng-tap directive ?

Thanks !
