### ISSUE TITLE
Breaks other directives

### ISSUE THREAD

**Issue by sebastianzillessen** [ajoslin/angular-mobile-nav#80]
Hello,

I'm using your module in my phonegap app and I'm using the angular-leaflet-directive (https://github.com/tombatossals/angular-leaflet-directive/). Unfortunately the directive does not load correctly, when it is in the `<mobile-view>` element. It seems like the directive has an empty size when it is displayed because there is only one tile.

I already wrote a request here https://github.com/tombatossals/angular-leaflet-directive/issues/168.

Maybe someone has a great idea how to fix that?

Thanks!

**Comment by ajoslin** [comment]
hmm, have you played with the css rules?

**Comment by ajoslin** [comment]
Could you create a reproduce scenario?

**Comment by sebastianzillessen** [comment]
I set this up.

You can see it here: http://jsfiddle.net/8dYp4/

I included both views, so you can see the difference.

PS: you can also simulate the behavior of resizing the window...

**Comment by ajoslin** [comment]
That demo for me on Mac OS X Chrome 30.0.1599 shows nothing for either ng-view or mobile-view

**Comment by sebastianzillessen** [comment]
Could you try it with Safari? 

It doesn't work for me in Chrome as well, I get the following errors:

```
Uncaught SecurityError: Blocked a frame with origin "http://www.google.de" from accessing a frame with origin "http://jsfiddle.net". Protocols, domains, and ports must match.
Uncaught SecurityError: Blocked a frame with origin "http://fiddle.jshell.net" from accessing a frame with origin "http://jsfiddle.net". Protocols, domains, and ports must match.
Refused to execute script from 'https://raw.github.com/ajoslin/angular-mobile-nav/master/mobile-nav.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. (index):1
Refused to execute script from 'https://raw.github.com/tombatossals/angular-leaflet-directive/master/dist/angular-leaflet-directive.js' because its MIME type ('text/plain') is not executable, and strict MIME type checking is enabled. (index):1
Uncaught Error: No module: leaflet-directive angular.min.js:17
```

Seems to be a problem of chrome and the external resources i included...
But in Safari it works fine.

**Comment by rody7val** [comment]
It means that the server `https://raw.github.com/` send a Javascript HTTP response with `Content-Type: text/plain` and Chrome not load the Javascript. Just download the javascript at your localhost.
