### ISSUE TITLE
Binding inside $navigate.go() doesn't work - AngularJS 1.2.1

### ISSUE THREAD

**Issue by 18112013** [ajoslin/angular-mobile-nav#84]
There seems to be a problem with curly braces inside $navigate.go() in AngularJS 1.2.1.

For example:

```
<a href="" ng-click="$navigate.go('/test/{{ something.id }}')">Test</a>
```

It redirects to /test/{{ something.id }} instead of /test/1234 (the actual id).

**Comment by ajoslin** [comment]
In ng-click you are already inside an angular expression, so you don't need to `{{}}`.

Try this:
`ng-click="$navigate.go('/test/' + something.id)"`

**Comment by 18112013** [comment]
It works, thank you!
`{{}}` inside .go() worked on previous versions on AngularJS, didn't thought of that.
