### ISSUE TITLE
up to 10 second delay on reverse transition 

### ISSUE THREAD

**Issue by NoWayJA** [ajoslin/angular-mobile-nav#85]
Firstly I want to say that I love this library, it is lightweight and fantasticly flexible - I am sure the angular-jqm will be gr8 too, but this library is hard to beat...
One problem I have on an app is in which everything works with one exception. The app has three levels and you navigate by swiping left and right. On the deepest level if you swipe right, the reverse transition can take up to ten seconds before it fires (on IOS 7.03 - with Cordova 3.1). 
If the swipe is changed for a click it works fine
If I change to a swipe left to do this action it works fine
On Chrome it works fine
If I use the IOS emulator it works fine
If I put an alert in, the alert happens instantly and after hitting OK it slides back fine
If I open Safari inspector (to the emulator) and try to console log, it mysteriously starts to work fine.
If I navigate from the third level to the first level it works fine.

Has anyone seen anything like this, it really is most peculiar as it is a combination of the swipe-right and destination that causes upto a ten second delay before the animation runs.

**Comment by ajoslin** [comment]
Coming soon: new view directive/service for angular 1.2, pulld out of angular-jqm.

**Comment by ajoslin** [comment]
If someone can fix this now that would be great, but just letting people know that I do have a plan for something here...

**Comment by NoWayJA** [comment]
So mysteriously the app is now working fine on IOS 7.04 ..... It could be to do with IOS I am guessing. If I see it again I will try and post more info.  Great to hear about the new directive - just want to re-iterate this library is my first choice for angular mobile nav and I hope it continues to live on :)
