### ISSUE TITLE
Add option to navigate to a page backwards

### ISSUE THREAD

**Issue by ajoslin** [ajoslin/angular-mobile-nav#9]
Add option to `go` so user can make it backwards.  Perhaps `$navigate.go('/page', [overrideTransition, direction])`.

If second parameter is a boolean, it will take that for reverse override.  Else it will take second parameter for a transition override and third parameter as reverse.  Or would direction of -1 or 1 be more intuitive?

If a page is recorded as having reverse direction, it will always reverse itself (going to it in reverse will slide like it's backwards, and going back from it will slide like it's going forwards).

Usecase: Start up app, want to make it look like going 'back' without actually having something in history.  Eg home page with a logout button going 'back' to login screen.

**Comment by Urigo** [comment]
Looks very easy, did you implement it already or should i pull request?

**Comment by ajoslin** [comment]
Hey Urigo! It'd be awesome if you could PR it, I'm low on time for the next week or two.  Thanks :-)

**Comment by whitneyland** [comment]
@Urigo - that would be great.  Would love to help test.

Are you going to give it a shot?

**Comment by whitneyland** [comment]
To clarify, is this issue just about navigation logic or about reversing the slide animation?

It would be helpful just to be able to explicitly reverse like this:
      $navigate.go('/','slide-out');  
      $navigate.go('/','slide-in');  

I saw something about in-out is the css, but not sure if it's there yet...

**Comment by ajoslin** [comment]
That would require too much change, methinks.  It would be good just to have a `isReverse` boolean or perhaps a `-1` or `1` direction, defaulting to one.  Which would just put a `this.reverse = true` on the page object, which would make it always reverse whatever it would normally do (so forward for back, reverse for non-back)

**Comment by whitneyland** [comment]
Agreed Andy that approach would be simple and work fine.
I here by offer a bounty of a free beer ($10 paypal donation) to the person who makes it happen so it works on iOS 5 or greater and Android 4 or greater.
Offer good to you, Urigo, or anyone else who wants to take a shot.
Cheers

Date: Tue, 5 Feb 2013 16:40:11 -0800

**Comment by ajoslin** [comment]
Haha, sounds awesome.  You have now motivated me to do it.  I will get it done after my exam later today...

(...and I don't know why I'm checking my e-mail when I should be studying for the exam that starts in 30 minutes... :laughing: )

**Comment by ajoslin** [comment]
Landed in 07c9f9fe1e61efcb3ce485c4b5902148bc36e47d

**Comment by whitneyland** [comment]
Beer bounty paid to andytjoslin@gmail.com !
